Separate bats and vimscript tests suite on CI.

diff --git a/test/run b/test/run
--- a/test/run
+++ b/test/run
@@ -17,56 +17,127 @@ set -o privileged
 set -o nounset
 set -o errexit
 
-TEST_DIRECTORY="$(cd "$(dirname "$0")" && pwd)" &&
-  export TEST_DIRECTORY
-
-TEST_DEPS_DIR="${TEST_DIRECTORY}/../test_lib" &&
-  export TEST_DEPS_DIR
+TEST_DIRECTORY="$(cd "$(dirname "$0")" && pwd)"
+TEST_DEPS_DIR="${TEST_DIRECTORY}/../test_lib"
+export TEST_DEPS_DIR
+export TEST_DIRECTORY
 
 BATS_EXECUTABLE="${TEST_DIRECTORY}/../test_lib/bats-core/bin/bats"
-
-git submodule init && git submodule update
 
 if [[ -z "${DOTFILES_BASH_DIR:-}" ]]; then
   DOTFILES_BASH_DIR=$(cd "${TEST_DIRECTORY}" && dirname "$(pwd)") &&
     export DOTFILES_BASH_DIR
 fi
 
-if [[ $# -eq 0 ]]; then
-  # shellcheck disable=2206
-  TEST_DIRS=(${TEST_DIRECTORY}/{install,Bash})
-  VADER_TEST_DIRS="${TEST_DIRECTORY}/Nvim"
-else
-  declare -ag BATS_SPEC=()
-  declare -ag VADER_SPEC=()
+git submodule init && git submodule update
 
-  for spec in "$@"; do
-    case "${spec: -5}" in
-    '.bats') BATS_SPEC+=("${spec}") ;;
-    'vader') VADER_SPEC+=("${spec}") ;;
+function main() {
+
+  if [[ $# -eq 0 ]]; then
+    # shellcheck disable=2206
+    TEST_DIRS=(${TEST_DIRECTORY}/{install,Bash})
+    VADER_TEST_DIRS="${TEST_DIRECTORY}/Nvim/*"
+  fi
+
+  _get_opts "$@"
+
+  _run_bats_tests
+  _run_vim_tests
+}
+
+function _usage() {
+  echo "  Usage:"
+  echo "    ${BASH_SOURCE[0]} [arguments]"
+  echo ""
+  echo "  Arguments:"
+  echo "    -h, --help       Display this help message"
+  echo "    -v, --vim-only   Run vimscript test suite only"
+  echo "    -b, --bats-only  Run bats test suite only"
+  echo "    --suite=SUITE    Provide space-delimited tests file paths"
+}
+
+function _get_opts() {
+  for param in "$@"; do
+    shift
+    case "${param}" in
+    "--help") set -- "$@" "-h" ;;
+    "--vim-only") set -- "$@" "-v" ;;
+    "--bats-only") set -- "$@" "-b" ;;
+    "--suite") set -- "$@" "-s" ;;
+    *) set -- "$@" "${param}" ;;
     esac
   done
-fi
 
-export TEMP_DIR="/tmp/dotfiles-vimscript-test"
-rm -rf "${TEMP_DIR}"
-mkdir -p "${TEMP_DIR}"
+  OPTIND=1
+  while getopts ":hvbs:" opt; do
+    case "${opt}" in
+    "h")
+      _usage
+      exit 0
+      ;;
+    "v")
+      export VIM_ONLY=1
+      _run_vim_tests
+      exit $?
+      ;;
+    "b")
+      export BATS_ONLY=1
+      _run_bats_tests
+      exit $?
+      ;;
+    "s")
+      declare -ag BATS_SPEC=()
+      declare -ag VADER_SPEC=()
 
-#cp "${TEST_DIRECTORY}/../nvim/init.vim" "${HOME}/.vim/vimrc"
+      for spec in ${OPTARG}; do
+        case "${spec: -5}" in
+        '.bats') BATS_SPEC+=("${spec}") ;;
+        'vader') VADER_SPEC+=("${spec}") ;;
+        esac
+      done
+      ;;
+    \?)
+      echo "Invalid option: -${OPTARG} requires an argument"
+      echo ""
+      _usage 1>&2
+      exit 1
+      ;;
+    esac
+  done
 
-cat >"${TEMP_DIR}/mini-vimrc" <<-VIMRC
+  shift $((OPTIND - 1))
+}
+
+function _run_vim_tests() {
+  export TEMP_DIR="/tmp/dotfiles-vimscript-test"
+  rm -rf "${TEMP_DIR}"
+  mkdir -p "${TEMP_DIR}"
+
+  cat >"${TEMP_DIR}/mini-vimrc" <<-VIMRC
 set runtimepath+=${TEST_DEPS_DIR:0}/vader.vim
 set shell=/bin/bash
 scriptnames
 VIMRC
 
-if [[ -n "${BATS_SPEC[*]:-}" ]] || [[ -n "${TEST_DIRS[*]:-}" ]]; then
-  eval "${BATS_EXECUTABLE} ${CI:+--tap} --recursive" \
-    "${TEST_DIRS[@]:-${BATS_SPEC[@]}}"
-fi
+  if [[ -n "${VADER_SPEC[*]}" ]] || [[ -n "${VIM_ONLY:-}" ]]; then
+    eval "vim -EsNu ${TEMP_DIR}/mini-vimrc -c" \
+      "'Vader! ${VADER_SPEC[*]:-${VADER_TEST_DIRS:-${TEST_DIRECTORY}/Nvim/*}}'" \
+      "> /dev/null"
+  fi
+}
 
-if [[ -n "${VADER_SPEC[*]:-}" ]] || [[ -n "${VADER_TEST_DIRS:-}" ]]; then
-  eval "vim -EsNu ${TEMP_DIR}/mini-vimrc -c" \
-    "'Vader! ${VADER_SPEC[*]:-${VADER_TEST_DIRS}/*}'" \
-    "> /dev/null"
-fi
+function _run_bats_tests() {
+  if [[ -n "${BATS_SPEC[*]}" ]] || [[ -n "${TEST_DIRS[*]}" ]] ||
+    [[ -n "${BATS_ONLY:-}" ]]; then
+
+    if [[ -n "${BATS_ONLY:-}" ]]; then
+      # shellcheck disable=2206
+      TEST_DIRS=(${TEST_DIRECTORY}/{install,Bash})
+    fi
+
+    eval "${BATS_EXECUTABLE} ${CI:+--tap} --recursive" \
+      "${BATS_SPEC[@]:-${TEST_DIRS[@]:-}}"
+  fi
+}
+
+main "$@"
