bash: Add function to cd to current dir in vifm.

diff --git a/bash/profile.d/functions b/bash/profile.d/functions
--- a/bash/profile.d/functions
+++ b/bash/profile.d/functions
@@ -24,3 +24,17 @@ function hicat() {
   fi
 
 }
+
+#
+vifm() {
+
+  local dest=""
+  dest="$(command vifm --choose-dir -)"
+
+  if [ -z "$dest" ]; then
+    echo 'Directory picking cancelled/failed'
+    return 1
+  fi
+
+  cd "$dest" || return
+}
