bash: Add `main` function for prompt.

diff --git a/bash/profile.d/prompt b/bash/profile.d/prompt
--- a/bash/profile.d/prompt
+++ b/bash/profile.d/prompt
@@ -11,7 +11,6 @@ function enable_color_support() {
 
 }
 
-
 function prompt_git() {
 
   local symbol='';
@@ -66,6 +65,15 @@ function prompt_git() {
 
 } 
 
+function _exit_status() {
+
+    if [ "$?" == "0" ]; then
+      echo -e "${green}"
+    else
+      echo -e "${red}"
+    fi
+
+}
 
 function set_prompts() {
 
@@ -96,16 +104,6 @@ function set_prompts() {
 
   fi
 
-  function _exit_status() {
-
-    if [ "$?" == "0" ]; then
-      echo -e "${green}"
-    else
-      echo -e "${red}"
-    fi
-
-  }
-
   PS1="\\n\\[${bold}\\]"
   PS1+="\\[${green}\\]"
   PS1+="\$(_exit_status \" \") ➜  "
@@ -123,7 +121,14 @@ function set_prompts() {
   trap 'echo -ne "${dimgrey}"' DEBUG
 }
 
-set_prompts
+function main() {
+  enable_color_support
+  set_prompts
+}
 
+main
+
+# cleanup
 unset -f enable_color_support
+unset -f main
 unset -f set_prompts
